# Generated by Django 3.2.4 on 2021-08-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Modificación'),
        ),
    ]
